// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by runnng the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATlGAlo2H2-3-OHZfFy07Oko_7epZZ9Xo',
    appId: '1:40884904628:web:3b2440d6ea1dc336946de1',
    messagingSenderId: '40884904628',
    projectId: 'lebronjames3404324',
    authDomain: 'lebronjames3404324.firebaseapp.com',
    storageBucket: 'lebronjames3404324.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfEPjbNtJXqRn3LmNjHDWRxE-pE78TXME',
    appId: '1:40884904628:android:f171d1ae80b0ff0a946de1',
    messagingSenderId: '40884904628',
    projectId: 'lebronjames3404324',
    storageBucket: 'lebronjames3404324.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9DV3cARJwaUevR79P6PAYEM_ezx34s5E',
    appId: '1:40884904628:ios:760f27de4ac33052946de1',
    messagingSenderId: '40884904628',
    projectId: 'lebronjames3404324',
    storageBucket: 'lebronjames3404324.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9DV3cARJwaUevR79P6PAYEM_ezx34s5E',
    appId: '1:40884904628:ios:760f27de4ac33052946de1',
    messagingSenderId: '40884904628',
    projectId: 'lebronjames3404324',
    storageBucket: 'lebronjames3404324.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATlGAlo2H2-3-OHZfFy07Oko_7epZZ9Xo',
    appId: '1:40884904628:web:52b4a655aa1dd86c946de1',
    messagingSenderId: '40884904628',
    projectId: 'lebronjames3404324',
    authDomain: 'lebronjames3404324.firebaseapp.com',
    storageBucket: 'lebronjames3404324.firebasestorage.app',
  );
}
